name: RAG Agent CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t rag-agent .

      - name: Set up DVC
        run: pip install dvc
    
      - name: Pull DVC data
        run: dvc pull

      - name: Run Knowledge Base Ingestion (inside container)
        run: docker run --rm -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" -v "$(pwd)/vector_db:/app/chromadb" -v "$(pwd)/data/documents:/app/data/" rag-agent python ingest.py

      - name: Run Evaluation script (inside container)
        run: docker run --rm -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" -e LANGSMITH_API_KEY="${{ secrets.LANGSMITH_API_KEY }}" -v "$(pwd)/vector_db:/app/chromadb" rag-agent python src/evaluation/evaluator.py

      - name: Upload Evaluation Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rag-evaluation-results
          path: rag_evaluation_results.csv
          if-no-files-found: ignore

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push your_docker_hub_username/rag-agent-ci:latest
